### ISSUE TITLE
钱包模块：恢复json钱包，私钥恢复的钱包地址与hrp: lat不一致

### ISSUE THREAD

**Issue by weimjsam** [aviland/platoncli-java#4]
环境 ：win10
jdk：Oracle jdk 8.0.2910.10

问题：【钱包模块】恢复json钱包，私钥恢复的钱包地址与hrp: lat不一致

![图片](https://user-images.githubusercontent.com/28893617/126464043-08c60e6b-f87c-4257-986d-c42605365626.png)

**Comment by aviland** [comment]
原代码中在此处未读取config，所以会出现hrp错误。通过强制读取config，修复了此bug

**Comment by weimjsam** [comment]
commit 8d92375e39e9102fc55925530621e34c94e9bccd
新版已修复
