### ISSUE TITLE
交易模块：发送已签名16进制功能缺失

### ISSUE THREAD

**Issue by weimjsam** [aviland/platoncli-java#5]
环境 ：win10
jdk：Oracle jdk 8.0.2910.10

问题：【交易模块】发送已签名16进制功能缺失

**Comment by aviland** [comment]
原设计文档中未包含此功能。通过您的反馈，我在tx模块中新增了tx_sendSignedHexData命令，该命令可以直接通过节点发送16进制数据。
命令样例如下：
```
java -jar platoncli-java-jar-with-dependencies.jar tx_sendSignedHexData --hexData 0x*********
```

**Comment by weimjsam** [comment]
commit a3933981ce9fa0dfed70db9ec0e3ba1cb6159665
新版验证通过
